### ISSUE TITLE
Resolve query using info for hard deleted entities

### ISSUE THREAD

**Issue by ezequielzacca** [silentium-labs/merlin-gql#4]
### Subject of the issue
When hard deleting a typeorm entity, a subscription will fail if any related entity data is asked for

### Your environment
* version of merlin_gql: 0.1.9
* version of node: v10.15.0
* version of typeorm: 0.2.25

### Steps to reproduce
Create 2 typeorm entities related. Hard delete a record, ask via delete subscription for the deleted record and ask in the subscription a field from the related entity

### Expected behaviour
We should get the subscription result when deleting the entity

### Actual behaviour
We get an error because the entity no longer exists and typeorm is trying to query the data using the requested info

**Comment by sebargarcia** [comment]
fixed in 0.2.24-rc.4
