### ISSUE TITLE
Reverse engineered database schema

### ISSUE THREAD

**Issue by sebargarcia** [silentium-labs/merlin-gql#5]
### Proposal
Reverse engineered database schema

It would be good to have a reverse-engineered database schema, something like [typeorm-model-generator](https://github.com/Kononnable/typeorm-model-generator), to generate models based on tables and resolvers.

**Comment by ezequielzacca** [comment]
We could fork [typeorm-model-generator](https://github.com/Kononnable/typeorm-model-generator) and integrate it into our ocliff commands workflow @sebargarcia

**Comment by sebargarcia** [comment]
ok, I will look into this
