### ISSUE TITLE
Refactor merlin-gql decorators

### ISSUE THREAD

**Issue by sebargarcia** [silentium-labs/merlin-gql#54]
Decorators in OT files must decorate entity models and not OT models per se. 
This could improve a lot the functionality of merlin-gql. 
In this way, we could rely only on entity data and use only OT files to decide what to expose to graphql API.

**Comment by ezequielzacca** [comment]
We managed to refactor a big chunk of code and a few potential headaches in the future by doing this change. We should be very proud! 
Now the only purpose of the OT Files during execution time is to add the TypeGraphQL Metadata to the TypeORM Entities and are not necessary on the resolvers.
